# Generated by Django 6.0.5 on 2026-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugbytestutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturant',
            name='type',
            field=models.CharField(choices=[('IN', 'Indian'), ('IT', 'Italian'), ('MX', 'Mexican'), ('CH', 'Chinese'), ('TH', 'Thai'), ('JP', 'Japanese')], default='IT', max_length=2),
            preserve_default=False,
        ),
    ]
