# Generated by Django 6.0.5 on 2026-06-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugbytestutorial', '0002_resturant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturant',
            old_name='type',
            new_name='resturant_type',
        ),
    ]
